### ISSUE TITLE
Tools link not working

### ISSUE THREAD

**Issue by haseeb-heaven** [cppchriscpp/nes-starter-kit#23]
External tools required as shown [here ](https://github.com/cppchriscpp/nes-starter-kit/blob/master/guide/section_1/setting_up_your_tools.md) is not working.

**REQUIRED**
Download Tools : http://cpprograms.net/devnull/nes_starter_kit_tools.zip

link seems to be dead.

**Comment by cppchriscpp** [comment]
Hello! Thank you for bringing this to my attention.

The link appears to be up for me, however Chrome seems to have started blocking it recently. 

It seems to be because it is served over http, whereas github is https. Here's the page chrome shows when you get it to work: https://support.google.com/chrome/answer/6261569?p=mixed_content_downloads&visit_id=637522325765770496-2883918358&rd=1

For right now, if you right click the link and hit "save as" it should let you bypass this. I will work on finding a home for it somewhere with ssl enabled to avoid Chrome's new behavior. Thank you again for bringing this up!

**Comment by cppchriscpp** [comment]
That was quicker/easier than I thought - here's a new URL that actually uses https: https://devnull.nes.science/nes_starter_kit_tools.zip - I'll update the documentation to reference this now.

**Comment by cppchriscpp** [comment]
This should be fixed as of 9918caf7f1d4e4183062ebc741131a73aad121b7 - let me know if you run into any additional issues.

Thanks again for bringing this up, and giving me all the details I needed to resolve this quickly!

**Comment by haseeb-heaven** [comment]
> This should be fixed as of [9918caf](https://github.com/cppchriscpp/nes-starter-kit/commit/9918caf7f1d4e4183062ebc741131a73aad121b7) - let me know if you run into any additional issues.
> 
> Thanks again for bringing this up, and giving me all the details I needed to resolve this quickly!

Thanks the new link is working now.
